apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - testdomain.invoicemate.tech
      secretName: backend-tls-cert
  rules:
    - host: testdomain.invoicemate.tech
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-api-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-api-svc
                port:
                  number: 80
